package com.example.friendupp.model

import com.example.friendupp.Categories.Category
import com.google.android.gms.maps.model.LatLng
import com.google.firebase.firestore.GeoPoint


data class Activity(
    var image: String?,
    val id: String,
    val title: String,
    val start_time: String,
    val creator_id: String,
    val description: String,
    val creator_username: String,
    val creator_name: String,
    var creator_profile_picture: String,
    var end_time: String,
    var geoHash: Any?,
    var lat: Any?,
    var lng: Any?,
    var custom_location: String?,
    val minUserCount: Int,
    val maxUserCount: Int,
    val disableChat: Boolean,
    val likes: Int,
    var invited_users: ArrayList<String>,
    val participants_profile_pictures: HashMap<String, String>,
    val participants_usernames: HashMap<String, String>,
    val creation_time: String,
    val location: GeoPoint?,
    val pictures: HashMap<String, String>,
    val enableActivitySharing: Boolean,
    val disableNotification: Boolean,
    val privateChat: Boolean,
    val public:Boolean,
    var participants_ids: ArrayList<String>,
    val participantConfirmation:Boolean,
    var requests: ArrayList<String>,
    var reports:Int,    var tags: ArrayList<String>,

    ) : java.io.Serializable {
    constructor() : this(
        image=null,
        id = "",
        title = "Hiking Adventure",
        start_time="",
        creator_id="",
        description="Join us for an exciting hiking adventure in the mountains!",
        creator_username="",
        creator_name="",
        creator_profile_picture="",
        end_time="",
        geoHash=null,
        lat=null,
        lng=null,
        custom_location=null,
        minUserCount= 0,
        maxUserCount=100,
        disableChat = false,
        likes=0,
        invited_users=ArrayList(),
        participants_profile_pictures=HashMap(),
        participants_usernames=HashMap(),
        creation_time="",
        location=null,
        pictures=HashMap(),
        enableActivitySharing = false,
        disableNotification = false,
        privateChat = false,
        public=false,
         participants_ids =ArrayList(),
        participantConfirmation=false,
        requests=ArrayList(),
        reports=0,
        tags=ArrayList(),
    )
}